/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AboutComponent {}
  interface AboutComponentAttributes extends StencilHTMLAttributes {}

  interface HomeComponent {}
  interface HomeComponentAttributes extends StencilHTMLAttributes {}

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AboutComponent': Components.AboutComponent;
    'HomeComponent': Components.HomeComponent;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'about-component': Components.AboutComponentAttributes;
    'home-component': Components.HomeComponentAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLAboutComponentElement extends Components.AboutComponent, HTMLStencilElement {}
  var HTMLAboutComponentElement: {
    prototype: HTMLAboutComponentElement;
    new (): HTMLAboutComponentElement;
  };

  interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {}
  var HTMLHomeComponentElement: {
    prototype: HTMLHomeComponentElement;
    new (): HTMLHomeComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'about-component': HTMLAboutComponentElement
    'home-component': HTMLHomeComponentElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'about-component': HTMLAboutComponentElement;
    'home-component': HTMLHomeComponentElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
